Repository fridge-rescue/fridge-rescue-client, pull requests merged in 2023-12, with the labels that each got.

#3 fridge-rescue #1 레이아웃 추가
  index.html
  package.json
  src/App.tsx
  src/components/common/Example.tsx
  src/components/layout/PageLayout.tsx
  src/main.tsx
  src/pages/ExamplePage.tsx
  src/routes/Router.tsx
  src/styles/globalStyle.ts
  src/styles/theme.ts
  yarn.lock
Labels: enhancement

#9 냉장고를부탁해 #4 navBar 생성
  package.json
  src/App.tsx
  src/assets/logo.png
  src/components/layout/PageLayout.tsx
  src/components/navbar/NavBar.tsx
  yarn.lock
Labels: enhancement

#12 냉장고를부탁해#8 레시피카드 컴포넌트 작성
  .eslintrc.cjs
  src/components/common/LargeRecipeCard.tsx
  src/components/common/SmallRecipeCard.tsx
  src/components/layout/Index.tsx
  src/components/layout/header/Header.tsx
Labels: enhancement

#13 냉장고를부탁해 #10 로그인 페이지 생성
  .eslintrc.cjs
  src/components/common/BasicButton.tsx
  src/components/common/BasicInput.tsx
  src/components/layout/Index.tsx
  src/components/layout/PageLayout.tsx
  src/components/layout/header/Header.tsx
  src/pages/SignIn.tsx
  src/routes/Router.tsx
  yarn.lock
Labels: enhancement

#14 냉장고를부탁해 #11 회원가입 페이지 생성
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/routes/Router.tsx
Labels: enhancement

#17 냉장고를부탁해 #16 공용 Confirm 모달 컴포넌트 생성
  src/components/common/ConfirmModal.tsx
  src/components/layout/PageLayout.tsx
Labels: enhancement

#19 냉장고를부탁해 #15 케러셀 슬라이드 추가
  package.json
  src/App.tsx
  src/components/common/CarouselSlider.tsx
  src/components/common/RecipeCard.tsx
  src/components/common/SmallRecipeCard.tsx
  src/components/header/Header.tsx
  src/hooks/useCardStyle.ts
  src/pages/Index.tsx
  src/routes/Router.tsx
  yarn.lock
Labels: enhancement

#21 냉장고를부탁해 #20 알림 사이드바 생성
  src/components/common/BasicTitle.tsx
  src/components/common/CarouselSlider.tsx
  src/components/common/RecipeCard.tsx
  src/components/common/SideBar.tsx
  src/components/header/Header.tsx
  src/pages/Index.tsx
Labels: enhancement

#22 냉장고를부탁해 #18 마이페이지 UI 구현
  .eslintrc.cjs
  src/components/common/ConfirmModal.tsx
  src/components/common/RecipeCard.tsx
  src/components/header/Header.tsx
  src/components/layout/PageLayout.tsx
  src/components/navbar/NavBar.tsx
  src/components/pages/myPage/NicknameEdit.tsx
  src/components/pages/myPage/PasswordEdit.tsx
  src/components/pages/myPage/PushList.tsx
  src/constants/menu.ts
  src/pages/MyPage.tsx
  src/routes/Router.tsx
  src/store/menu.ts
  src/styles/globalStyle.ts
Labels: enhancement

#25 냉장고를부탁해 #24 레시피 스크랩 페이지 구현
  src/components/common/BasicButton.tsx
  src/components/common/BasicTitle.tsx
  src/components/common/ConfirmModal.tsx
  src/components/header/Header.tsx
  src/components/navbar/NavBar.tsx
  src/pages/Index.tsx
  src/pages/MyPage.tsx
  src/pages/Scrap.tsx
  src/routes/Router.tsx
Labels: enhancement

#27 냉장고를 부탁해 #23 레시피등록 이미지&설명 업로드form 생성, 재료 목록 버튼 공통컴포넌트 생성
  src/components/IngredientSearchForm.tsx
  src/components/RecipeStep.tsx
  src/components/common/BasicButton.tsx
  src/components/common/BasicInput.tsx
  src/components/common/IngredientList.tsx
  src/components/header/Header.tsx
  src/components/pages/myPage/NicknameEdit.tsx
  src/components/pages/myPage/PasswordEdit.tsx
  src/hooks/useIngredient.ts
  src/pages/AddRecipe.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/routes/Router.tsx
Labels: enhancement

#29 냉장고를 부탁해 #28 레시피 등록 버그 수정
  src/components/common/IngredientList.tsx
  src/pages/AddRecipe.tsx
Labels: bug

#31 냉장고를 부탁해 #30 나의 냉장고 페이지 생성
  src/components/IngredientSearchForm.tsx
  src/components/common/RecipeCard.tsx
  src/hooks/useSelectItem.ts
  src/pages/AddRecipe.tsx
  src/pages/MyRefrigerator.tsx
  src/routes/Router.tsx
Labels: enhancement

#34 냉장고를부탁해 #33 코드 리팩토링 및 이벤트 추가
  src/components/common/BasicButton.tsx
  src/components/common/SideBar.tsx
  src/components/header/Header.tsx
  src/components/navbar/NavBar.tsx
  src/pages/AddRecipe.tsx
Labels: bug, enhancement

#36 냉장고를 부탁해 #32 레시피 등록 페이지 재료검색 및 등록 플로우 수정
  src/components/IngredientSearchForm.tsx
  src/hooks/useIngredient.ts
  src/pages/AddRecipe.tsx
  src/pages/MyRefrigerator.tsx
Labels: bug, enhancement
