Repository fridge-rescue/fridge-rescue-client, pull requests merged in 2024-01, with the labels that each got.

#38 냉장고를부탁해 #35 요리 후기 등록 페이지
  package.json
  src/components/common/BasicTextArea.tsx
  src/components/common/DragAndDrop.tsx
  src/pages/ReviewPost.tsx
  src/pages/SignIn.tsx
  src/routes/Router.tsx
  yarn.lock
Labels: enhancement

#40 냉장고를부탁해 #39 레시피 자세히보기 페이지
  src/components/pages/Recipe/RecipeReview.tsx
  src/components/pages/Recipe/RecipeReviewList.tsx
  src/pages/RecipeView.tsx
  src/routes/Router.tsx
Labels: enhancement

#42 냉장고를부탁해 #41 레시피 페이지 생성
  src/components/common/ConfirmModal.tsx
  src/components/common/RecipeCard.tsx
  src/components/navbar/NavBar.tsx
  src/pages/Recipe.tsx
  src/pages/RecipeView.tsx
  src/pages/ReviewPost.tsx
  src/routes/Router.tsx
Labels: enhancement

#43 냉장고 구조대 #37 냉장고 페이지 UI 수정 및 전달 데이터 변경
  src/components/IngredientInfo.tsx
  src/components/IngredientSearchForm.tsx
  src/hooks/useIngredient.ts
  src/hooks/useSelectItem.ts
  src/pages/AddRecipe.tsx
  src/pages/MyRefrigerator.tsx
Labels: bug, enhancement

#46 냉장고를 부탁해 #44
  src/components/IngredientInfo.tsx
  src/components/IngredientSearchForm.tsx
  src/hooks/useIngredient.ts
  src/pages/AddRecipe.tsx
  src/pages/MyRefrigerator.tsx
Labels: bug, enhancement

#47 냉장고를부탁해 #45 json-server 세팅
  package.json
  src/mocks/db.json
  yarn.lock
Labels: enhancement

#49 냉장고를 부탁해#48 json-server 목데이터 생성 및 부분 적용
  src/api/axiosInstance.ts
  src/api/recipe/getNewRecipe.ts
  src/components/CardList.tsx
  src/components/common/FallBack.tsx
  src/constants/api.ts
  src/constants/queryKey.ts
  src/hooks/api/queryClient.ts
  src/mocks/db.json
  src/pages/Index.tsx
  src/types/recipeType.ts
Labels: enhancement

#51 냉장고를 부탁해#50 axios 인터셉터 설정
  src/api/axiosInstance.ts
  src/api/interceptors.ts
  src/api/recipe/getNewRecipe.ts
  src/constants/api.ts
  src/types/tokenType.ts
Labels: enhancement

#53 냉장고를 부탁해 develop -> main 정기 병합
  .eslintrc.cjs
  index.html
  package.json
  src/App.tsx
  src/api/axiosInstance.ts
  src/api/interceptors.ts
  src/api/recipe/getNewRecipe.ts
  src/assets/logo.png
  src/components/CardList.tsx
  src/components/IngredientInfo.tsx
  src/components/IngredientSearchForm.tsx
  src/components/RecipeStep.tsx
  src/components/common/BasicButton.tsx
  src/components/common/BasicInput.tsx
  src/components/common/BasicTextArea.tsx
  src/components/common/BasicTitle.tsx
  src/components/common/CarouselSlider.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/DragAndDrop.tsx
  src/components/common/Example.tsx
  src/components/common/FallBack.tsx
  src/components/common/IngredientList.tsx
  src/components/common/RecipeCard.tsx
  src/components/common/SideBar.tsx
  src/components/header/Header.tsx
  src/components/layout/PageLayout.tsx
  src/components/navbar/NavBar.tsx
  src/components/pages/Recipe/RecipeReview.tsx
  src/components/pages/Recipe/RecipeReviewList.tsx
  src/components/pages/myPage/NicknameEdit.tsx
  src/components/pages/myPage/PasswordEdit.tsx
  src/components/pages/myPage/PushList.tsx
  src/constants/api.ts
  src/constants/menu.ts
  src/constants/queryKey.ts
  src/hooks/api/queryClient.ts
  src/hooks/useCardStyle.ts
  src/hooks/useSelectItem.ts
  src/main.tsx
  src/mocks/db.json
  src/pages/AddRecipe.tsx
  src/pages/ExamplePage.tsx
  src/pages/Index.tsx
  src/pages/MyPage.tsx
  src/pages/MyRefrigerator.tsx
  src/pages/Recipe.tsx
  src/pages/RecipeView.tsx
  src/pages/ReviewPost.tsx
  src/pages/Scrap.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/routes/Router.tsx
  src/store/menu.ts
  src/styles/globalStyle.ts
  src/styles/theme.ts
  src/types/recipeType.ts
  src/types/tokenType.ts
  vite.config.ts
  yarn.lock
Labels: deploy

#54 냉장고를 부탁해 #52 나의 냉장고 재료 수정 삭제 방식 변경 및 UI 변경
  src/api/ingredient/getIngredient.ts
  src/api/ingredient/ingredientSuggest.ts
  src/components/AddIngredientInfo.tsx
  src/components/MyIngredientList.tsx
  src/constants/api.ts
  src/constants/queryKey.ts
  src/mocks/db.json
  src/pages/MyRefrigerator.tsx
  src/types/ingredientType.ts
Labels: bug, enhancement

#58 냉장고를부탁해 #57 프록시 및 환경변수 설정
  package.json
  vite.config.ts
  yarn.lock
Labels: enhancement

#56 냉장고를 부탁해 #55 슬라이드 애니메이션 수정
  src/api/axiosInstance.ts
  src/components/CardList.tsx
  src/components/MyIngredientList.tsx
  src/components/common/CarouselSlider.tsx
  src/constants/api.ts
Labels: bug, enhancement

#60 냉장고를 부탁해 #59 서버 URL 설정
  src/api/auth/signUp.ts
  src/api/axiosInstance.ts
  src/api/recipe/getNewRecipe.ts
  src/components/CardList.tsx
  src/constants/api.ts
  src/pages/SignUp.tsx
  vite.config.ts
Labels: bug, enhancement

#62 냉장고를부탁해 #61 메인페이지 캐러셀 수정
  package.json
  src/components/common/Carousel.tsx
  src/components/common/CarouselSlider.tsx
  src/pages/Index.tsx
  yarn.lock
Labels: bug, enhancement

#65 냉장고를부탁해 #64 파일 및 폴더 정리
  src/api/auth.ts
  src/api/cook.ts
  src/api/fridge.ts
  src/api/ingredient/getIngredient.ts
  src/api/ingredient/ingredientSuggest.ts
  src/api/member.ts
  src/api/notification.ts
  src/api/recipe.ts
  src/api/report.ts
  src/api/review.ts
  src/components/common/CardList.tsx
  src/components/pages/Recipe/RecipeStep.tsx
  src/components/pages/fridge/AddIngredientInfo.tsx
  src/components/pages/fridge/IngredientSearchForm.tsx
  src/components/pages/fridge/MyIngredientList.tsx
  src/mocks/recipe.ts
  src/pages/AddRecipe.tsx
  src/pages/MyRefrigerator.tsx
  src/pages/RecipeView.tsx
  src/routes/Router.tsx
  src/types/exampleTypes.ts
  src/utils/exampleUtils.ts
Labels: enhancement

#67 냉장고를부탁해 #66 레시피 상세페이지 데이터 연동
  src/api/recipe.ts
  src/constants/queryKey.ts
  src/pages/Index.tsx
  src/pages/RecipeView.tsx
  src/pages/SignUp.tsx
  src/styles/theme.ts
  src/types/recipeType.ts
  src/utils/formatDate.ts
Labels: enhancement

#68 냉장고를 부탁해#59 회원가입 서버 연동 작업
  package.json
  src/api/auth.ts
  src/api/fridge.ts
  src/components/common/BasicInput.tsx
  src/components/common/ConfirmModal.tsx
  src/constants/api.ts
  src/pages/Index.tsx
  src/pages/SignUp.tsx
  src/types/ingredientType.ts
  yarn.lock
Labels: enhancement

#71 냉장고를부탁해 #69 이미지 모달 공용 컴포넌트 생성
  package.json
  src/components/common/ImageModal.tsx
  src/components/pages/Recipe/RecipeReview.tsx
  src/pages/AddRecipe.tsx
  src/pages/RecipeView.tsx
  yarn.lock
Labels: enhancement

#72 냉장고를 부탁해 #70 이메일 로그인 기능 구현
  src/api/auth.ts
  src/api/interceptors.ts
  src/components/header/Header.tsx
  src/constants/api.ts
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/routes/PrivateRoute.tsx
  src/routes/Router.tsx
  src/store/auth.ts
  src/utils/getRefreshToken.ts
Labels: enhancement

#75 냉장고를 부탁해 #73 토큰 저장방식 수정, axios 인터셉터 무한 요청 버그 수정
  src/api/axiosInstance.ts
  src/api/fridge.ts
  src/api/interceptors.ts
  src/components/header/Header.tsx
  src/components/pages/fridge/MyIngredientList.tsx
  src/hooks/api/queryClient.ts
  src/pages/SignIn.tsx
  src/routes/PrivateRoute.tsx
Labels: bug

#77 냉장고를부탁해 #74 재료 수정 페이지 생성 및 요리 완료 flow 수정
  src/components/common/IngredientList.tsx
  src/components/pages/myPage/EmailAuth.tsx
  src/constants/menu.ts
  src/pages/EditIngredient.tsx
  src/pages/MyPage.tsx
  src/pages/RecipeView.tsx
  src/pages/ReviewPost.tsx
  src/routes/Router.tsx
Labels: bug, enhancement

#80 냉장고를 부탁해 #76 사용자 등록 레시피 추가
  src/api/auth.ts
  src/api/interceptors.ts
  src/api/recipe.ts
  src/components/pages/Recipe/RecipeStep.tsx
  src/components/pages/fridge/MyIngredientList.tsx
  src/constants/queryKey.ts
  src/pages/AddRecipe.tsx
  src/pages/SignIn.tsx
Labels: bug, enhancement, wontfix

#82 냉장고를부탁해 #81 리뷰 데이터 연동 및 무한스크롤 구현
  package.json
  src/api/recipe.ts
  src/api/review.ts
  src/components/pages/Recipe/RecipeReview.tsx
  src/components/pages/Recipe/RecipeReviewList.tsx
  src/constants/queryKey.ts
  src/types/reviewType.ts
  yarn.lock
Labels: enhancement

#84 냉장고를 부탁해 #83 재료 등록 페이지 데이터 전송 방식을 수정 및 재료의 양 추가
  src/api/recipe.ts
  src/components/pages/Recipe/RecipeStep.tsx
  src/components/pages/Recipe/UsedIngrident.tsx
  src/pages/AddRecipe.tsx
Labels: bug, enhancement

#87 냉장고를 부탁해 #86 나의 냉장고 페이지 완성
  src/api/axiosInstance.ts
  src/api/fridge.ts
  src/api/interceptors.ts
  src/api/recipe.ts
  src/components/pages/fridge/AddIngredientInfo.tsx
  src/components/pages/fridge/MyIngredientList.tsx
  src/constants/queryKey.ts
  src/pages/AddRecipe.tsx
  src/pages/MyRefrigerator.tsx
  src/types/ingredientType.ts
Labels: enhancement

#89 냉장고를부탁해 #85 #88 요리 완료 후 재료 수정과 리뷰 등록 기능 추가
  src/App.tsx
  src/api/cook.ts
  src/api/review.ts
  src/components/common/DragAndDrop.tsx
  src/components/common/ScrollToTop.tsx
  src/components/pages/fridge/IngredientAccordion.tsx
  src/constants/queryKey.ts
  src/hooks/useDebounce.tsx
  src/pages/EditIngredient.tsx
  src/pages/RecipeView.tsx
  src/pages/ReviewPost.tsx
  src/types/ingredientType.ts
Labels: enhancement

#92 냉장고를 부탁해 #90 로그인 후 이메일 인증 기능 구현
  src/api/auth.ts
  src/api/interceptors.ts
  src/api/recipe.ts
  src/components/header/Header.tsx
  src/components/pages/myPage/EmailAuth.tsx
  src/constants/api.ts
  src/constants/queryKey.ts
  src/pages/SignUp.tsx
Labels: enhancement

#96 냉장고를 부탁해 #93 검색시 추천 검색어 노출 기능 추가
  src/api/recipe.ts
  src/api/search.ts
  src/components/common/CardList.tsx
  src/components/pages/Recipe/UsedIngrident.tsx
  src/components/pages/fridge/IngredientSearchForm.tsx
  src/constants/api.ts
  src/constants/queryKey.ts
  src/hooks/useRecipe.ts
  src/pages/AddRecipe.tsx
  src/pages/UpdateRecipe.tsx
  src/routes/Router.tsx
  src/types/ingredientType.ts
Labels: enhancement

#97 냉장고를 부탁해 #93 알림기능 추가
  package.json
  src/api/notification.ts
  src/components/common/SideBar.tsx
  src/components/header/Header.tsx
  src/components/pages/myPage/PushList.tsx
  src/constants/api.ts
  src/constants/queryKey.ts
  src/hooks/useNotification.ts
  src/types/notification.ts
  yarn.lock
Labels: enhancement

#99 냉장고를부탁해 #98 신고 기능 추가
  src/api/member.ts
  src/api/recipe.ts
  src/api/report.ts
  src/components/common/ConfirmModal.tsx
  src/components/pages/Recipe/RecipeReview.tsx
  src/components/pages/Recipe/ReportModal.tsx
  src/constants/api.ts
  src/constants/queryKey.ts
  src/pages/RecipeView.tsx
  src/pages/ReviewEdit.tsx
  src/pages/Scrap.tsx
Labels: enhancement

#100 냉장고를부탁해 #95 북마크 기능 추가
  src/api/auth.ts
  src/api/recipe.ts
  src/pages/RecipeView.tsx
  src/pages/Scrap.tsx
  src/types/recipeType.ts
Labels: bug, enhancement

#102 냉장고를 부탁해 #101 카드컴포넌트 하단정보 수정 및 회원가입 유효성 검사 추가
  package.json
  src/api/recipe.ts
  src/components/common/CardList.tsx
  src/components/common/RecipeCard.tsx
  src/components/pages/fridge/AddIngredientInfo.tsx
  src/components/pages/fridge/MyIngredientList.tsx
  src/pages/Recipe.tsx
  src/pages/SignUp.tsx
  yarn.lock
Labels: bug, enhancement

#105 냉장고를 부탁해 #104 검색기능 구현 완료
  src/api/search.ts
  src/components/header/Header.tsx
  src/components/pages/fridge/IngredientSearchForm.tsx
  src/constants/api.ts
  src/constants/queryKey.ts
  src/pages/SearchResult.tsx
  src/routes/Router.tsx
  src/store/search.ts
  src/types/searchResultType.ts
Labels: enhancement

#106 냉장고를부탁해 #103 메인페이지 데이터 연동
  src/api/recipe.ts
  src/components/common/CardList.tsx
  src/components/common/Carousel.tsx
  src/components/common/RecipeCard.tsx
  src/components/pages/fridge/IngredientAccordion.tsx
  src/constants/queryKey.ts
  src/pages/EditIngredient.tsx
  src/pages/Index.tsx
  src/pages/RecipeView.tsx
  src/types/recipeType.ts
Labels: bug, enhancement

#109 냉장고를부탁해 #107 레시피 스크랩 페이지 및 버그 수정
  package.json
  src/api/member.ts
  src/components/pages/myPage/PasswordEdit.tsx
  src/pages/RecipeView.tsx
  src/pages/Scrap.tsx
  src/store/menu.ts
  yarn.lock
Labels: bug, enhancement

#111 냉장고를 부탁해 #108 레시피 작성 페이지 및 레시피 페이지 및 검색 페이지 버그 수정 및 일부 UI 변경
  src/components/common/RecipeCard.tsx
  src/components/pages/Recipe/RecipeStep.tsx
  src/components/pages/Recipe/UsedIngrident.tsx
  src/components/pages/fridge/MyIngredientList.tsx
  src/hooks/useCardStyle.ts
  src/hooks/useRecipe.ts
  src/pages/AddRecipe.tsx
  src/pages/MyRefrigerator.tsx
  src/pages/Recipe.tsx
  src/pages/SearchResult.tsx
Labels: bug

#113 냉장고를부탁해 #110 레시피 페이지, 마이페이지 구현 및 버그 수정
  src/api/member.ts
  src/api/recipe.ts
  src/components/header/Header.tsx
  src/components/pages/Recipe/LatestRecipe.tsx
  src/components/pages/Recipe/PopularRecipe.tsx
  src/components/pages/Recipe/RecipeReview.tsx
  src/components/pages/Recipe/RecipeReviewList.tsx
  src/components/pages/Recipe/RecommendedRecipe.tsx
  src/components/pages/myPage/CompletedCooking.tsx
  src/components/pages/myPage/EmailAuth.tsx
  src/components/pages/myPage/MyCooking.tsx
  src/components/pages/myPage/MyRecipe.tsx
  src/constants/menu.ts
  src/constants/queryKey.ts
  src/pages/Index.tsx
  src/pages/MyPage.tsx
  src/pages/Recipe.tsx
  src/pages/ReviewPost.tsx
  src/types/recipeType.ts
Labels: bug, enhancement

#115 냉장고를 부탁해 #112 SSE를 이용한 실시간 알림 받기 기능
  package.json
  src/components/header/Header.tsx
  src/constants/api.ts
  src/routes/Router.tsx
  yarn.lock
Labels: enhancement

#117 냉장고를 부탁해 #116 레시피 수정 기능 완성
  src/api/member.ts
  src/api/notification.ts
  src/api/recipe.ts
  src/components/common/SideBar.tsx
  src/components/pages/Recipe/RecipeStep.tsx
  src/components/pages/Recipe/UsedIngrident.tsx
  src/components/pages/myPage/PushList.tsx
  src/constants/api.ts
  src/constants/queryKey.ts
  src/hooks/useRecipe.ts
  src/pages/AddRecipe.tsx
  src/pages/RecipeView.tsx
  src/pages/UpdateRecipe.tsx
Labels: bug, enhancement

#118 냉장고를 부탁해 develop -> main 정기 병합
  package.json
  src/api/member.ts
  src/api/notification.ts
  src/api/recipe.ts
  src/components/common/SideBar.tsx
  src/components/header/Header.tsx
  src/components/pages/Recipe/RecipeStep.tsx
  src/components/pages/Recipe/UsedIngrident.tsx
  src/components/pages/myPage/PushList.tsx
  src/constants/api.ts
  src/constants/queryKey.ts
  src/hooks/useRecipe.ts
  src/pages/AddRecipe.tsx
  src/pages/RecipeView.tsx
  src/pages/UpdateRecipe.tsx
  src/routes/Router.tsx
  yarn.lock
Labels: deploy

#119 fix : 버그 수정
  src/api/recipe.ts
  src/pages/RecipeView.tsx
Labels: bug

#120 fix : 예외처리 추가
  src/components/pages/myPage/CompletedCooking.tsx
  src/components/pages/myPage/MyRecipe.tsx
Labels: bug

#121 fix: 알림 라우팅처리 수정
  src/hooks/useNotification.ts
Labels: bug
